package com.ysu.tour.dao;

import com.ysu.tour.pojo.Category;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy_table
     *
     * @mbggenerated
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy_table
     *
     * @mbggenerated
     */
    Category selectByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy_table
     *
     * @mbggenerated
     */
    List<Category> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Category record);

    List<Category> fenyeselect(Integer start);
    int selectcountall();
    List<Category> fenleiselect(@Param("month") String month,
                                @Param("day") String day,@Param("pay") String pay,
                                @Param("people") String people,@Param("play") String play,@Param("start") int start);
    List<Category> fuzzyselect(@Param("name") String name,@Param("start") int start);
    int countfuzzyall(String name);
    int countfenleiall(@Param("month") String month,
                                @Param("day") String day,@Param("pay") String pay,
                                @Param("people") String people,@Param("play") String play);
    int insertPlay(@Param("strategyId") int strategyId,@Param("playId") int playId);
}