package com.ysu.tour.dao;

import com.ysu.tour.pojo.People;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PeopleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer peoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_table
     *
     * @mbggenerated
     */
    int insert(People record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_table
     *
     * @mbggenerated
     */
    People selectByPrimaryKey(Integer peoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_table
     *
     * @mbggenerated
     */
    List<People> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(People record);



//    以下是管理员

    List<People> sysselectAll();
    int sysupdateStatus(@Param("status") Integer status, @Param("id") Integer id);
    int sysinsert(People people);

}