package com.ysu.tour.dao;

import com.ysu.tour.pojo.Play;
import java.util.List;

public interface PlayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_name
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer playId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_name
     *
     * @mbggenerated
     */
    int insert(Play record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_name
     *
     * @mbggenerated
     */
    Play selectByPrimaryKey(Integer playId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_name
     *
     * @mbggenerated
     */
    List<Play> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play_name
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Play record);
}