package com.ysu.tour.dao;

import com.ysu.tour.pojo.Season;
import java.util.List;

public interface SeasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table season_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer seasonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table season_table
     *
     * @mbggenerated
     */
    int insert(Season record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table season_table
     *
     * @mbggenerated
     */
    Season selectByPrimaryKey(Integer seasonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table season_table
     *
     * @mbggenerated
     */
    List<Season> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table season_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Season record);
    Season selectById(Integer id);
}