package com.ysu.tour.pojo;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_id
     *
     * @mbggenerated
     */
    private Integer sMasterId;

    public Integer getsMasterId() {
        return sMasterId;
    }

    public void setsMasterId(Integer sMasterId) {
        this.sMasterId = sMasterId;
    }

    private String sGotime;

    public String getsGotime() {
        return sGotime;
    }

    public void setsGotime(String sGotime) {
        this.sGotime = sGotime;
    }

    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_time
     *
     * @mbggenerated
     */
    private String sTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_name
     *
     * @mbggenerated
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_cover
     *
     * @mbggenerated
     */
    private String sCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_text
     *
     * @mbggenerated
     */
    private String sText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_day
     *
     * @mbggenerated
     */
    private Integer sDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_pay
     *
     * @mbggenerated
     */
    private Integer sPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_status
     *
     * @mbggenerated
     */
    private Integer sStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_com_num
     *
     * @mbggenerated
     */
    private Integer sComNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_cli_num
     *
     * @mbggenerated
     */
    private Integer sCliNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_look_num
     *
     * @mbggenerated
     */
    private Integer sLookNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_pic_id
     *
     * @mbggenerated
     */
    private Integer sPicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_people_id
     *
     * @mbggenerated
     */
    private Integer sPeopleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_play_id
     *
     * @mbggenerated
     */
    private Integer sPlayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_table.s_season_id
     *
     * @mbggenerated
     */
    private Integer sSeasonId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_id
     *
     * @return the value of strategy_table.s_id
     *
     * @mbggenerated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_id
     *
     * @param sId the value for strategy_table.s_id
     *
     * @mbggenerated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_time
     *
     * @return the value of strategy_table.s_time
     *
     * @mbggenerated
     */
    public String getsTime() {
        return sTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_time
     *
     * @param sTime the value for strategy_table.s_time
     *
     * @mbggenerated
     */
    public void setsTime(String sTime) {
        this.sTime = sTime == null ? null : sTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_name
     *
     * @return the value of strategy_table.s_name
     *
     * @mbggenerated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_name
     *
     * @param sName the value for strategy_table.s_name
     *
     * @mbggenerated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_cover
     *
     * @return the value of strategy_table.s_cover
     *
     * @mbggenerated
     */
    public String getsCover() {
        return sCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_cover
     *
     * @param sCover the value for strategy_table.s_cover
     *
     * @mbggenerated
     */
    public void setsCover(String sCover) {
        this.sCover = sCover == null ? null : sCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_text
     *
     * @return the value of strategy_table.s_text
     *
     * @mbggenerated
     */
    public String getsText() {
        return sText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_text
     *
     * @param sText the value for strategy_table.s_text
     *
     * @mbggenerated
     */
    public void setsText(String sText) {
        this.sText = sText == null ? null : sText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_day
     *
     * @return the value of strategy_table.s_day
     *
     * @mbggenerated
     */
    public Integer getsDay() {
        return sDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_day
     *
     * @param sDay the value for strategy_table.s_day
     *
     * @mbggenerated
     */
    public void setsDay(Integer sDay) {
        this.sDay = sDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_pay
     *
     * @return the value of strategy_table.s_pay
     *
     * @mbggenerated
     */
    public Integer getsPay() {
        return sPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_pay
     *
     * @param sPay the value for strategy_table.s_pay
     *
     * @mbggenerated
     */
    public void setsPay(Integer sPay) {
        this.sPay = sPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_status
     *
     * @return the value of strategy_table.s_status
     *
     * @mbggenerated
     */
    public Integer getsStatus() {
        return sStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_status
     *
     * @param sStatus the value for strategy_table.s_status
     *
     * @mbggenerated
     */
    public void setsStatus(Integer sStatus) {
        this.sStatus = sStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_com_num
     *
     * @return the value of strategy_table.s_com_num
     *
     * @mbggenerated
     */
    public Integer getsComNum() {
        return sComNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_com_num
     *
     * @param sComNum the value for strategy_table.s_com_num
     *
     * @mbggenerated
     */
    public void setsComNum(Integer sComNum) {
        this.sComNum = sComNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_cli_num
     *
     * @return the value of strategy_table.s_cli_num
     *
     * @mbggenerated
     */
    public Integer getsCliNum() {
        return sCliNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_cli_num
     *
     * @param sCliNum the value for strategy_table.s_cli_num
     *
     * @mbggenerated
     */
    public void setsCliNum(Integer sCliNum) {
        this.sCliNum = sCliNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_look_num
     *
     * @return the value of strategy_table.s_look_num
     *
     * @mbggenerated
     */
    public Integer getsLookNum() {
        return sLookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_look_num
     *
     * @param sLookNum the value for strategy_table.s_look_num
     *
     * @mbggenerated
     */
    public void setsLookNum(Integer sLookNum) {
        this.sLookNum = sLookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_pic_id
     *
     * @return the value of strategy_table.s_pic_id
     *
     * @mbggenerated
     */
    public Integer getsPicId() {
        return sPicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_pic_id
     *
     * @param sPicId the value for strategy_table.s_pic_id
     *
     * @mbggenerated
     */
    public void setsPicId(Integer sPicId) {
        this.sPicId = sPicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_people_id
     *
     * @return the value of strategy_table.s_people_id
     *
     * @mbggenerated
     */
    public Integer getsPeopleId() {
        return sPeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_people_id
     *
     * @param sPeopleId the value for strategy_table.s_people_id
     *
     * @mbggenerated
     */
    public void setsPeopleId(Integer sPeopleId) {
        this.sPeopleId = sPeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_play_id
     *
     * @return the value of strategy_table.s_play_id
     *
     * @mbggenerated
     */
    public Integer getsPlayId() {
        return sPlayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_play_id
     *
     * @param sPlayId the value for strategy_table.s_play_id
     *
     * @mbggenerated
     */
    public void setsPlayId(Integer sPlayId) {
        this.sPlayId = sPlayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_table.s_season_id
     *
     * @return the value of strategy_table.s_season_id
     *
     * @mbggenerated
     */
    public Integer getsSeasonId() {
        return sSeasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_table.s_season_id
     *
     * @param sSeasonId the value for strategy_table.s_season_id
     *
     * @mbggenerated
     */
    public void setsSeasonId(Integer sSeasonId) {
        this.sSeasonId = sSeasonId;
    }
}