package com.ysu.tour.pojo;

public class CategoryPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_pic_table.spic_id
     *
     * @mbggenerated
     */
    private Integer spicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_pic_table.s_id
     *
     * @mbggenerated
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_pic_table.spic_url
     *
     * @mbggenerated
     */
    private String spicUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_pic_table.spic_id
     *
     * @return the value of strategy_pic_table.spic_id
     *
     * @mbggenerated
     */
    public Integer getSpicId() {
        return spicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_pic_table.spic_id
     *
     * @param spicId the value for strategy_pic_table.spic_id
     *
     * @mbggenerated
     */
    public void setSpicId(Integer spicId) {
        this.spicId = spicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_pic_table.s_id
     *
     * @return the value of strategy_pic_table.s_id
     *
     * @mbggenerated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_pic_table.s_id
     *
     * @param sId the value for strategy_pic_table.s_id
     *
     * @mbggenerated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_pic_table.spic_url
     *
     * @return the value of strategy_pic_table.spic_url
     *
     * @mbggenerated
     */
    public String getSpicUrl() {
        return spicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_pic_table.spic_url
     *
     * @param spicUrl the value for strategy_pic_table.spic_url
     *
     * @mbggenerated
     */
    public void setSpicUrl(String spicUrl) {
        this.spicUrl = spicUrl == null ? null : spicUrl.trim();
    }
}