package com.ysu.tour.pojo;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_table.c_id
     *
     * @mbggenerated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_table.s_id
     *
     * @mbggenerated
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_table.c_text
     *
     * @mbggenerated
     */
    private String cText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_table.c_time
     *
     * @mbggenerated
     */
    private String cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_table.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_table.cu_id
     *
     * @mbggenerated
     */
    private Integer cuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_table.c_id
     *
     * @return the value of comment_table.c_id
     *
     * @mbggenerated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_table.c_id
     *
     * @param cId the value for comment_table.c_id
     *
     * @mbggenerated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_table.s_id
     *
     * @return the value of comment_table.s_id
     *
     * @mbggenerated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_table.s_id
     *
     * @param sId the value for comment_table.s_id
     *
     * @mbggenerated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_table.c_text
     *
     * @return the value of comment_table.c_text
     *
     * @mbggenerated
     */
    public String getcText() {
        return cText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_table.c_text
     *
     * @param cText the value for comment_table.c_text
     *
     * @mbggenerated
     */
    public void setcText(String cText) {
        this.cText = cText == null ? null : cText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_table.c_time
     *
     * @return the value of comment_table.c_time
     *
     * @mbggenerated
     */
    public String getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_table.c_time
     *
     * @param cTime the value for comment_table.c_time
     *
     * @mbggenerated
     */
    public void setcTime(String cTime) {
        this.cTime = cTime == null ? null : cTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_table.u_id
     *
     * @return the value of comment_table.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_table.u_id
     *
     * @param uId the value for comment_table.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_table.cu_id
     *
     * @return the value of comment_table.cu_id
     *
     * @mbggenerated
     */
    public Integer getCuId() {
        return cuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_table.cu_id
     *
     * @param cuId the value for comment_table.cu_id
     *
     * @mbggenerated
     */
    public void setCuId(Integer cuId) {
        this.cuId = cuId;
    }
}