package com.ysu.tour.pojo;

public class People {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people_table.peo_id
     *
     * @mbggenerated
     */
    private Integer peoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people_table.peo_name
     *
     * @mbggenerated
     */
    private String peoName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people_table.peo_id
     *
     * @return the value of people_table.peo_id
     *
     * @mbggenerated
     */
    public Integer getPeoId() {
        return peoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people_table.peo_id
     *
     * @param peoId the value for people_table.peo_id
     *
     * @mbggenerated
     */
    public void setPeoId(Integer peoId) {
        this.peoId = peoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people_table.peo_name
     *
     * @return the value of people_table.peo_name
     *
     * @mbggenerated
     */
    public String getPeoName() {
        return peoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people_table.peo_name
     *
     * @param peoName the value for people_table.peo_name
     *
     * @mbggenerated
     */
    public void setPeoName(String peoName) {
        this.peoName = peoName == null ? null : peoName.trim();
    }
}