package com.ysu.tour.pojo;

public class Play {

    private Integer playId;


    private String playName;


    private  String playStatus;


    public String getPlayStatus() {
        return playStatus;
    }

    public void setPlayStatus(String playStatus) {
        this.playStatus = playStatus;
    }

    public Integer getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play_name.play_id
     *
     * @param playId the value for play_name.play_id
     *
     * @mbggenerated
     */
    public void setPlayId(Integer playId) {
        this.playId = playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play_name.play_name
     *
     * @return the value of play_name.play_name
     *
     * @mbggenerated
     */
    public String getPlayName() {
        return playName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play_name.play_name
     *
     * @param playName the value for play_name.play_name
     *
     * @mbggenerated
     */
    public void setPlayName(String playName) {
        this.playName = playName == null ? null : playName.trim();
    }
}