package com.ysu.tour.pojo;

public class Season {

    private Integer seasonId;

    private String seasonName;

    private  String seasonStatus;

    public String getSeasonStatus() {
        return seasonStatus;
    }

    public void setSeasonStatus(String seasonStatus) {
        this.seasonStatus = seasonStatus;
    }

    public Integer getSeasonId() {
        return seasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column season_table.season_id
     *
     * @param seasonId the value for season_table.season_id
     *
     * @mbggenerated
     */
    public void setSeasonId(Integer seasonId) {
        this.seasonId = seasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column season_table.season_name
     *
     * @return the value of season_table.season_name
     *
     * @mbggenerated
     */
    public String getSeasonName() {
        return seasonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column season_table.season_name
     *
     * @param seasonName the value for season_table.season_name
     *
     * @mbggenerated
     */
    public void setSeasonName(String seasonName) {
        this.seasonName = seasonName == null ? null : seasonName.trim();
    }
}