package com.ysu.tour.pojo;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.u_status
     *
     * @mbggenerated
     */
    private Integer uStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.u_name
     *
     * @mbggenerated
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.u_email
     *
     * @mbggenerated
     */
    private String uEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.u_pwd
     *
     * @mbggenerated
     */
    private String uPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.u_gender
     *
     * @mbggenerated
     */
    private Integer uGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.u_age
     *
     * @mbggenerated
     */
    private Integer uAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.u_pic
     *
     * @mbggenerated
     */
    private String uPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.u_id
     *
     * @return the value of user_table.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.u_id
     *
     * @param uId the value for user_table.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.u_status
     *
     * @return the value of user_table.u_status
     *
     * @mbggenerated
     */
    public Integer getuStatus() {
        return uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.u_status
     *
     * @param uStatus the value for user_table.u_status
     *
     * @mbggenerated
     */
    public void setuStatus(Integer uStatus) {
        this.uStatus = uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.u_name
     *
     * @return the value of user_table.u_name
     *
     * @mbggenerated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.u_name
     *
     * @param uName the value for user_table.u_name
     *
     * @mbggenerated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.u_email
     *
     * @return the value of user_table.u_email
     *
     * @mbggenerated
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.u_email
     *
     * @param uEmail the value for user_table.u_email
     *
     * @mbggenerated
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.u_pwd
     *
     * @return the value of user_table.u_pwd
     *
     * @mbggenerated
     */
    public String getuPwd() {
        return uPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.u_pwd
     *
     * @param uPwd the value for user_table.u_pwd
     *
     * @mbggenerated
     */
    public void setuPwd(String uPwd) {
        this.uPwd = uPwd == null ? null : uPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.u_gender
     *
     * @return the value of user_table.u_gender
     *
     * @mbggenerated
     */
    public Integer getuGender() {
        return uGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.u_gender
     *
     * @param uGender the value for user_table.u_gender
     *
     * @mbggenerated
     */
    public void setuGender(Integer uGender) {
        this.uGender = uGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.u_age
     *
     * @return the value of user_table.u_age
     *
     * @mbggenerated
     */
    public Integer getuAge() {
        return uAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.u_age
     *
     * @param uAge the value for user_table.u_age
     *
     * @mbggenerated
     */
    public void setuAge(Integer uAge) {
        this.uAge = uAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.u_pic
     *
     * @return the value of user_table.u_pic
     *
     * @mbggenerated
     */
    public String getuPic() {
        return uPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.u_pic
     *
     * @param uPic the value for user_table.u_pic
     *
     * @mbggenerated
     */
    public void setuPic(String uPic) {
        this.uPic = uPic == null ? null : uPic.trim();
    }
}